Version 2.0

diff --git a/pt b/pt
--- a/pt
+++ b/pt
@@ -1,73 +1,125 @@
-#!/bin/bash
+#!/bin/sh
 
-# Author: ANAS.B (dy@ducky)
+set -e
 
-MPLAYER="play"
+lang=
+query=
+tmpfile=
 
-# Check if a directory exists
-ifdir(){
-if [ ! -d $1 ];then
-    mkdir -p $1 
-fi
-}
-check(){
-	#checks if a variable is an empty string
-	if [ -z $1 ];then
-		exit
-	fi
+dmenu=false
+fzf=false
+
+download_dir="$HOME/.pt"
+version="dev 2.0"
+
+sname="$(basename $0)"
+
+show_help(){
+    printf "
+    Usage:  $sname [ -q ARG ] [ -l ARG ] [vfdm]
+
+         -q  For the search query !
+               Example: $sname -q hallo
+
+         -l  To add a language code
+               Example  $sname -l en -q hello
+
+         -d  To download the audios and store them locally. The default path is ${download_dir}
+                
+                * For each query a folder will be created and store all the audios inside it !
+                * Support offline usage. 
+
+         -v  Show version
+
+         -m  To use dmenu
+
+         -f  To use fzf
+"
 }
 
-check_if_installed(){
-for dep in dmenu cut grep curl play; do
-  command_exists "$dep" || echo "\n $dep is a required dependency, please install it"
-done
-}
-scraper(){
+getsource(){
 
-	scraper=$(curl "https://${LANG}.wiktionary.org/wiki/${QUERY,,}" | grep -Eo "//upload[a-zA-Z0-9./?=_%:-]*\.+(ogg|mp3|wav|aac)")
-	check $scraper
-	echo "${scraper}"  > "${DIR}/${QUERY,,}"
-}
-audio(){
-    # Formats the url into a nice friendly input
-    ans=$(cut -d'/' -f8 "${DIR}/${QUERY,,}" | dmenu -l 5 -p "Select the audio file  : ")
-    check $ans
-    AUDIO_URL="$(grep $ans "${DIR}/${QUERY,,}" | head -n 1)"
-    $MPLAYER "https:${AUDIO_URL}"
+    trap cleanup INT QUIT TERM EXIT
+
+    query=$(printf "$query" | tr '[:upper:]' '[:lower:]')
+    tmpfile=`mktemp`
+
+    cleanup(){
+        [ -f $tmpfile ] && rm $tmpfile
+    }
+    curl -s "https://${lang:=en}.wiktionary.org/wiki/${query}" | \
+        grep -Eo '//upload[a-zA-Z0-9./?=_%:-]*\.+(ogg|mp3|wav|aac)' | sed 's/\/\//https:&/g' >$tmpfile
 }
 
-command_exists () {
-	command -v "$1" > /dev/null 2>&1
+show_version(){
+        printf "$sname Version: %s\n" "$version"
+        exit 0
 }
-if_exists(){
-# check if a the QUERY exists in /tmp/read_this
-    if test -f "${DIR}/${QUERY,,}"; then
-        audio && exit 
+
+
+check_dep(){
+    if ! command -v "$1";then
+        printf "$1 is not installed !\n" && exit 127
     fi
-scraper && audio
 }
 
-case $# in 
-	0)
-		TMP=$(cut -f 2 lang_codes | dmenu -l 10 -p "Select a language (Lowercase!) : ")
-		QUERY=$(echo "" | dmenu -p "Pronounce what  ?: ")
-		LANG=$(grep $TMP lang_codes | cut -f 1)
-		DIR="$HOME/.config/lang/${LANG}"
-		ifdir $DIR
-		check $QUERY
-		if_exists
-		;;
-	2)
-		LANG="$1"
-		QUERY="$2"
-		DIR="$HOME/.config/lang/${LANG}"
-		ifdir ${DIR}
-		if_exists
-		;;
-	*)
-		printf '\e[1;34m%-6s\e[m' "Command line usage:  pt lang_code search_query"
-		printf "\n"
-		printf '\e[1;34m%-6s\e[m' "Example           :  pt de hallo"
-		exit
-		;;
-esac
+_main_(){
+    if ls -A "$aud_dir" 2> /dev/null;then # check if a dir is not empty instead of existance
+        selected=$(ls "$aud_dir" | $1)
+        mpv "${aud_dir}/${selected}"
+        exit 0
+    else
+        getsource
+        if [ -s $tmpfile ];then
+            selected=$(rev $tmpfile | cut -d'/' -f 1 | rev | $1 )
+            grep $selected $tmpfile | mpv --playlist=-
+            [ $download ] && download_aud
+        else
+            printf "-> No results found for %s :/\n" "$query" >&2
+            exit 0
+        fi
+    fi
+}
+
+download_aud(){
+    mkdir -p "${aud_dir}" # Buggy
+    printf "Downloading the audios ..."
+    cat $tmpfile | parallel curl -O --output-dir "${aud_dir}" && printf "Download completed." \
+        || (printf "Enable to download the audio files !" && exit 1)
+}
+
+while getopts "q:hl:dfmv" OPT; do
+    case "$OPT" in 
+        h) show_help && exit 0 ;; 
+        q) query=$OPTARG ;;
+        l) lang=$OPTARG ;;
+        f) fzf=true;;
+        d) download=true ;;
+        m) dmenu=true ;;
+        v) show_version ;;
+        *) printf "Wrong usage !\n Show help with: $sname -h\n" >&2 && exit 1;;
+    esac
+done
+
+
+# If the query is empty or is not a casual word
+if ! expr "$query" : "[a-zA-Z]" 1>/dev/null; then
+    printf "Error: The query must be a non empty letter !\n" >&2  
+    exit 1
+fi
+
+[ $dmenu = "true" ] && [ $fzf = "true" ] && \
+    printf "Error: -m and -f are mutually exclusive and may only be used once\n" >&2 && exit 2
+
+aud_dir="${download_dir}/${query}"
+
+if $dmenu;then
+    check_dep dmenu
+     _main_ 'dmenu -l 10'
+elif $fzf
+then
+    check_dep fzf 
+    _main_ "fzf --reverse --height=40%"
+else
+    _main_ "head -n 1"
+fi
