NEW Generic Pronunciation+

diff --git a/pt b/pt
--- a/pt
+++ b/pt
@@ -2,6 +2,7 @@
 
 set -e
 
+PLAYER="mpv --quiet"
 dmenu=false
 fzf=false
 
@@ -18,16 +19,23 @@ sname="$(basename $0)"
 
 show_help(){
     printf "
-    ${Y}Usage:${N}  ${G}$sname${N} ${W}[ -q ARG ] [ -l ARG ] [vfdm]${N}
+    ${Y}Usage:${N}  ${G}$sname${N} ${W}( -q ARG | -p ARG ) [ -l ARG ] [vfdm]${N}
 
          ${Y}-q${N}  For the search query !
                Example: ${G}$sname${N} -q hallo
 
          ${Y}-l${N}  To add a language code
                Example  ${G}$sname${N} -l en -q hello
+	       Default language code : en ( english )
+
+         ${Y}-p${N}  For generic Pronunciation !
+               Example: ${G}$sname${N} -l en -p \"${W}He Who Has A Why To Live Can Bear Almost Any How${N}\"
+
+                        ${G}$sname${N} -p warum -l de
 
          ${Y}-d${N}  To download the audios and store them locally.
                 
+		${W}ONLY${N} for ${G}-q${N} option !
                 * For each query a folder will be created and store all the audios inside it !
                 * Support offline usage. 
 
@@ -44,7 +52,13 @@ show_help(){
 "
 }
 
-getsource(){
+
+show_version(){
+        printf "${G}$sname${N} ${W}Version:${N} ${Y}%s${N}\n" "$version"
+	exit 0
+}
+
+get_source_code(){
 
     trap cleanup INT QUIT TERM EXIT
 
@@ -59,45 +73,12 @@ getsource(){
         sed 's/\/\//https:&/g' >$tmpfile 
 }
 
-show_version(){
-        printf "${G}$sname${N} ${W}Version:${N} ${Y}%s${N}\n" "$version"
-        exit 0
+
+generic_pronunciation(){
+	$PLAYER "https://audio.dict.cc/speak.audio.php?type=wav&lang=${lang:=en}&text=$@" 2>/dev/null
+	exit 0
 }
 
-
-check_dep(){
-    if ! command -v "$1";then
-        printf "${R}$1 is not installed !${N}\n" && exit 127
-    fi
-}
-
-_main_(){
-
-    query=$(printf "$query" | tr -d ' ')
-    tmpfile=`mktemp`
-    aud_dir="${download_dir}/${lang:=en}/${query}"
-
-    if ls -A "$aud_dir" 2> /dev/null;then # check if a dir is not empty instead of existance
-        selected=$(ls "$aud_dir" | $1)
-        mpv --quiet "${aud_dir}/${selected}"
-        exit 0
-    else
-        getsource
-        if [ -s $tmpfile ];then
-            selected=$(rev $tmpfile | cut -d'/' -f 1 | rev | $1)
-            grep $selected $tmpfile | mpv --quiet --playlist=-
-            [ $download ] && download_aud
-	    exit 0
-        else
-	        error
-        fi
-    fi
-}
-
-error(){
-	printf "No audio files found for $query \nLanguage code Used : ${lang:=en}\n"
-	exit 1
-}
 
 download_aud(){
     mkdir -p "${aud_dir}" 
@@ -106,12 +87,53 @@ download_aud(){
         || (printf "${R}Enable to download the audio files !${N}\n" && exit 1)
 }
 
-while getopts "q:hl:dfmv" OPT; do
+dep_error(){
+    if ! command -v "$1" >/dev/null;then
+        printf "${R}$1 is not installed !${N}\n" && exit 127
+    fi
+}
+
+null_error(){
+	printf "No audio files found for $query \nLanguage code Used : ${lang:=en}\n" | $1
+	exit 1
+}
+
+
+arg_error(){
+    printf "${R}Error:${N} ${W}-m${N} and ${W}-f${N} are mutually exclusive and may only be used once\n" >&2 
+    exit 2
+}
+
+_main_(){
+
+    query=$(printf "$query" | tr -d ' ')
+    tmpfile=`mktemp`
+    aud_dir="${download_dir}/${lang:=en}/${query}"
+
+	if ls -A "$aud_dir" 2> /dev/null;then # check if a dir is not empty instead of existance
+		selected=$(ls "$aud_dir" | $1)
+		$PLAYER "${aud_dir}/${selected}" 2>/dev/null
+		exit 0
+	    else
+		get_source_code
+		if [ -s $tmpfile ];then
+		    selected=$(rev $tmpfile | cut -d'/' -f 1 | rev | $1)
+		    grep $selected $tmpfile | xargs -I {} $PLAYER {} 2>/dev/null
+		    [ $download ] && download_aud
+		    exit 0
+		else
+			null_error "$1"
+		fi
+	    fi
+}
+
+while getopts "q:hl:dfmvp:" OPT; do
     case "$OPT" in 
         h) show_help && exit 0 ;; 
         q) query=$OPTARG ;;
         l) lang=$OPTARG ;;
         f) fzf=true;;
+	p) generic_pronunciation "$OPTARG";;
         d) download=true ;;
         m) dmenu=true ;;
         v) show_version ;;
@@ -120,21 +142,21 @@ while getopts "q:hl:dfmv" OPT; do
 done
 
 # If the query is empty or is not a casual word
-if ! expr "$query" : "[a-zA-Z]" 1>/dev/null; then
-    printf "${R}Error:${N} The ${W}query${N} must be a non empty letter !\n" >&2  
+if ! expr "$query" : "[a-zA-Z]" 1>/dev/null;then
+	printf "${R}Error:${N} The ${W}query${N} must be a non empty letter !\n" >&2  
     exit 1
 fi
 
-[ $dmenu = "true" ] && [ $fzf = "true" ] && \
-    printf "${R}Error:${N} ${W}-m${N} and ${W}-f${N} are mutually exclusive and may only be used once\n" >&2 && exit 2
+[ $dmenu = "true" ] && [ $fzf = "true" ] && arg_error
 
 
 if $dmenu;then
-    check_dep dmenu
+    dep_error dmenu
      _main_ "dmenu -l 10"
+
 elif $fzf
 then
-    check_dep fzf 
+    dep_error fzf 
     _main_ "fzf --reverse --height=40%"
 else
     _main_ "head -n 1"
